# Generated by Django 4.2.4 on 2023-09-07 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReproductorMusic2', '0002_rename_genero_id_cancion_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancion',
            name='ruta',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
